# Site settings
title: Projet Initiation Science pour l'Ingénieur, Classification d'Image par Réseau de Neurone Artificiel
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zakari Benabdesselam
user_description: fan de cinéma et nouvelle technologie
user_title: Lycéen en Terminale S spécialité Science pour l'ingénieur
email: zakari-94@live.fr
twitter_username: lorem_ipsum
github_username:  https://github.com/zakbena
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
